# Django App Deployed to heroku
name: Django Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "abhayjhablog98" #Must be unique in Heroku
          heroku_email: "akj441@gmail.com"
        env:
          HD_DJANGO_SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
          HD_DJANGO_DEBUG: False
